//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ГалиевЧудоОбувь
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int OrderdItemID { get; set; }
        public int OrderID { get; set; }
        public int StockID { get; set; }
        public int Quantity { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
